# Generated by Django 6.0 on 2026-02-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='reset_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='reset_token',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
